version: "3"
services:
  webapi:
    image: traceipwebapi
    container_name: traceipwebapi
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    links:
      - redis

  redis:
    image: redis
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always